// ─── Designer Colors (용도별 분류) ──────────────────────────────────────────
const designerColors = {
    ui_web: [
        { name: '버셀 블루',        hex: '#0070F3' },
        { name: '성공 그린',        hex: '#00C853' },
        { name: '경고 앰버',        hex: '#FF6F00' },
        { name: '오류 레드',        hex: '#FF1744' },
        { name: '정보 틸',          hex: '#00BCD4' },
        { name: '링크 블루',        hex: '#1976D2' },
        { name: '비활성 그레이',    hex: '#9E9E9E' },
        { name: '다크 배경',        hex: '#121212' },
        { name: '카드 화이트',      hex: '#FAFAFA' },
        { name: '보더 그레이',      hex: '#E0E0E0' },
        { name: '포커스 블루',      hex: '#2563EB' },
        { name: '섀도우 블랙',      hex: '#0F172A' },
    ],
    brand_global: [
        { name: '애플 스페이스그레이', hex: '#1D1D1F' },
        { name: '구글 레드',           hex: '#EA4335' },
        { name: '스포티파이 그린',     hex: '#1DB954' },
        { name: '넷플릭스 레드',       hex: '#E50914' },
        { name: '슬랙 퍼플',           hex: '#4A154B' },
        { name: '디스코드 블러플',     hex: '#5865F2' },
        { name: '유튜브 레드',         hex: '#FF0000' },
        { name: '인스타그램 퍼플',     hex: '#C13584' },
        { name: '메타 블루',           hex: '#0866FF' },
        { name: '트위터 블루',         hex: '#1DA1F2' },
        { name: '아마존 오렌지',       hex: '#FF9900' },
        { name: '마이크로소프트 블루', hex: '#0078D4' },
        { name: '텐센트 블루',         hex: '#1878F3' },
        { name: '틱톡 블랙',           hex: '#010101' },
        { name: '링크드인 블루',       hex: '#0A66C2' },
        { name: '에어비앤비 레드',     hex: '#FF5A5F' },
    ],
    nature: [
        { name: '포레스트 그린',  hex: '#228B22' },
        { name: '스카이 블루',    hex: '#87CEEB' },
        { name: '딥 오션',        hex: '#006994' },
        { name: '선셋 오렌지',    hex: '#FF4500' },
        { name: '체리 블라썸',    hex: '#FFB7C5' },
        { name: '골든 샌드',      hex: '#C2B280' },
        { name: '모스 그린',      hex: '#8A9A5B' },
        { name: '라벤더 필드',    hex: '#967BB6' },
        { name: '오로라 그린',    hex: '#00FFCC' },
        { name: '산호초',         hex: '#FF6B6B' },
        { name: '크리스탈 레이크',hex: '#5DADE2' },
        { name: '가을 단풍',      hex: '#D35400' },
    ],
    pastel: [
        { name: '베이비 핑크',   hex: '#FFD1DC' },
        { name: '라벤더 미스트', hex: '#E6E6FA' },
        { name: '민트 크림',     hex: '#B5EAD7' },
        { name: '피치 블러쉬',   hex: '#FFCBA4' },
        { name: '베이비 블루',   hex: '#AED6F1' },
        { name: '버터 옐로우',   hex: '#FFF0AA' },
        { name: '라일락',        hex: '#D7B2FF' },
    ],
    neon_modern: [
        { name: '네온 핑크',      hex: '#FF10F0' },
        { name: '일렉트릭 블루',  hex: '#00B4FF' },
        { name: '네온 그린',      hex: '#39FF14' },
        { name: '사이버 옐로우',  hex: '#FFE600' },
        { name: '핫 오렌지',      hex: '#FF6A00' },
        { name: '매트릭스 그린',  hex: '#00FF41' },
        { name: 'UV 퍼플',        hex: '#7B00FF' },
        { name: '레이저 레드',    hex: '#FF003F' },
    ],
    earth: [
        { name: '테라코타',     hex: '#C27A54' },
        { name: '탄 베이지',    hex: '#D2B48C' },
        { name: '시에나',       hex: '#A0522D' },
        { name: '카키',         hex: '#C3AA7E' },
        { name: '샌드스톤',     hex: '#DEB887' },
        { name: '다크 초콜렛',  hex: '#4E2623' },
        { name: '올리브 드랩',  hex: '#6B7C3A' },
    ],
    monochrome: [
        { name: '퓨어 블랙',   hex: '#000000' },
        { name: '다크 차콜',   hex: '#212121' },
        { name: '차콜 그레이', hex: '#424242' },
        { name: '미디엄 그레이',hex: '#616161' },
        { name: '실버',        hex: '#9E9E9E' },
        { name: '라이트 그레이',hex: '#E0E0E0' },
        { name: '퓨어 화이트', hex: '#FFFFFF' },
    ]
};

// ─── Color Name References ──────────────────────────────────────────────────
const colorNameReferences = {
    '가을 단풍':    { hex: '#D35400', name_en: 'Autumn Leaf', tags: ['autumn', '오렌지', '붉은'] },
    '감청색':       { hex: '#1428A0', name_en: 'Royal Blue', tags: ['business', '전문', '파랑'] },
    '검정':         { hex: '#000000', name_en: 'Black', tags: ['contrast', '우아', '어둠'] },
    '골드':         { hex: '#FFD700', name_en: 'Gold', tags: ['premium', '화려', '럭셔리'] },
    '녹색':         { hex: '#00B050', name_en: 'Green', tags: ['natural', '성장', '자연'] },
    '네이비':       { hex: '#001F5B', name_en: 'Navy', tags: ['formal', '클래식', '신뢰'] },
    '네온 그린':    { hex: '#39FF14', name_en: 'Neon Green', tags: ['neon', '형광', '밝은'] },
    '라벤더':       { hex: '#967BB6', name_en: 'Lavender', tags: ['soft', '우아', '보라'] },
    '민트':         { hex: '#00B8A9', name_en: 'Mint', tags: ['fresh', '차분', '자연'] },
    '베이지':       { hex: '#C8A882', name_en: 'Beige', tags: ['elegant', '전통', '따뜻함'] },
    '보라':         { hex: '#7851A9', name_en: 'Purple', tags: ['luxury', '창의', '우아'] },
    '분홍':         { hex: '#FF69B4', name_en: 'Pink', tags: ['pink', '귀여움', '부드러움'] },
    '빨강':         { hex: '#FF0000', name_en: 'Red', tags: ['primary', '강렬', '위험'] },
    '살몬':         { hex: '#FA8072', name_en: 'Salmon', tags: ['warm', '소프트', '핑크'] },
    '스카이블루':   { hex: '#87CEEB', name_en: 'Sky Blue', tags: ['sky', '하늘', '맑음'] },
    '시안':         { hex: '#00BCD4', name_en: 'Cyan', tags: ['tech', '혁신', '청량'] },
    '아이보리':     { hex: '#FFFFF0', name_en: 'Ivory', tags: ['warm', '부드러운', '화이트'] },
    '오렌지':       { hex: '#FF6B00', name_en: 'Orange', tags: ['energy', '활동', '따뜻함'] },
    '청록':         { hex: '#20B2AA', name_en: 'Teal', tags: ['cool', '편안', '바다'] },
    '회색':         { hex: '#808080', name_en: 'Gray', tags: ['neutral', '중립', '차분'] },
    '흰색':         { hex: '#FFFFFF', name_en: 'White', tags: ['clean', '공간', '순수'] },
};

// ─── Design Inspiration Palettes ────────────────────────────────────────────
const designInspiration = [
    { name: '미니멀 모던', name_en: 'Minimal Modern', colors: ['#000000', '#FFFFFF', '#8B8B8B', '#E8E8E8'] },
    { name: '네온 나이트', name_en: 'Neon Night', colors: ['#FF10F0', '#FFE600', '#00B4FF', '#7B00FF'] },
    { name: '해양 휴가', name_en: 'Ocean Vacation', colors: ['#005377', '#00A8E8', '#00D9FF', '#B5EAD7'] },
    { name: '서로운 일몰', name_en: 'Deep Sunset', colors: ['#FF6B35', '#FFB627', '#C27A54', '#4E2623'] },
    { name: '숲의 꿈', name_en: 'Forest Dream', colors: ['#228B22', '#8A9A5B', '#DEB887', '#006994'] },
    { name: '리퀴드 글래스', name_en: 'Liquid Glass', colors: ['#E0F7FF', '#AED6F1', '#5DADE2', '#1A5276'] },
    { name: '다크 엘리건스', name_en: 'Dark Elegance', colors: ['#000000', '#212121', '#424242', '#9E9E9E'] },
    { name: '코랄 선셋', name_en: 'Coral Sunset', colors: ['#FF7F50', '#FF6B9D', '#FFD1DC', '#FFCBA4'] },
    { name: '어반 테크', name_en: 'Urban Tech', colors: ['#0070F3', '#212121', '#E0E0E0', '#FAFAFA'] },
    { name: '파스텔 드림', name_en: 'Pastel Dream', colors: ['#FFD1DC', '#B5EAD7', '#AED6F1', '#FFF0AA'] },
    { name: '브랜드 파워', name_en: 'Brand Power', colors: ['#E50914', '#1DB954', '#5865F2', '#FF9900'] },
    { name: '어스 톤', name_en: 'Earth Tone', colors: ['#C27A54', '#A0522D', '#DEB887', '#6B7C3A'] },
];

// ─── Today's Design Pick (Cards) ────────────────────────────────────────────
const designCards = [
    {
        id: '01',
        name: 'Night × Kiwi',
        category: '스포츠웨어 / 테크 / 스트릿 브랜딩',
        category_en: 'Sportswear / Tech / Street Branding',
        description: '어둠을 뚫고 나오는 형광의 대비\n강한 긴장감과 젊은 에너지를 동시에 만듭니다.',
        description_en: 'Fluorescent contrast piercing through darkness, creating strong tension and youthful energy.',
        colors: [
            { name: 'Midnight', hex: '#0A0A0A' },
            { name: 'Electric Kiwi', hex: '#DFFF00' }
        ]
    },
    {
        id: '02',
        name: 'Soft Shell',
        category: '라이프스타일 / 코스메틱 / 감성 매거진',
        category_en: 'Lifestyle / Cosmetics / Emotional Magazine',
        description: '파스텔 톤의 부드러움 속에 숨겨진 견고함\n편안하면서도 정돈된 분위기를 제안합니다.',
        description_en: 'Firmness hidden within pastel softness, proposing a comfortable yet organized atmosphere.',
        colors: [
            { name: 'Dusty Rose', hex: '#DCAE96' },
            { name: 'Sand Beige', hex: '#F5F5DC' }
        ]
    }
];

// ─── Design Guides ──────────────────────────────────────────────────────────
const designGuides = [
    {
        title: '60-30-10 법칙',
        title_en: '60-30-10 Rule',
        desc: '주조색 60%, 보조색 30%, 포인트색 10%의 황금 비율로 균형 잡힌 디자인을 완성하세요.',
        desc_en: 'Complete a balanced design with the golden ratio: 60% primary, 30% secondary, and 10% point color.',
        colors: ['#FFFFFF', '#F0F0F0', '#0070F3']
    },
    {
        title: '보색 대비 활용',
        title_en: 'Complementary Contrast',
        desc: '색상환의 반대편 색상을 사용하여 강렬한 시각적 효과를 주는 방법입니다.',
        desc_en: 'A method to create a powerful visual effect by using colors on the opposite side of the color wheel.',
        colors: ['#FF4500', '#00BFFF', '#FFD700']
    }
];

// ─── UI Translations ────────────────────────────────────────────────────────
const uiTranslations = {
    kr: {
        nav_picker: '피커',
        nav_library: '라이브러리',
        nav_today: '오늘의 픽',
        nav_inspiration: '움직이는 영감',
        nav_guide: '가이드',
        nav_my: '내 보관함',
        detail_mood: '색상 무드',
        detail_advice: '디자인 조언',
        detail_usage: '활용 분야',
        detail_similar: '비슷한 색상',
        detail_contrast: '가독성 테스트',
        btn_copy_hex: 'HEX 복사',
        btn_copy_rgb: 'RGB 복사',
        btn_reset: '리셋',
        btn_save: '보관함 저장',
        btn_share: '링크 공유',
        btn_close: '닫기',
        search_placeholder: '색상 이름이나 태그 검색...',
        empty_fav: '보관함이 비어 있습니다.',
        select_family: '색 계열 선택',
        keyboard_guide_title: '조작 방법',
        keyboard_guide_1: 'R / G / B 클릭: 채널 선택',
        keyboard_guide_2: '← →: 선택 채널 미세 조정',
        keyboard_guide_3: '스페이스바: 룰렛 재시작',
        inspiration_subtitle: '멈추면 팔레트가 나타납니다 • 색을 클릭하면 Color Picker로 이동',
        guide_subtitle: '색채에 대한 기초적이고 실용적인 지식들',
        library_subtitle: '용도별로 분류된 컬러 라이브러리',
        cat_all: '전체',
        cat_ui_web: 'UI/웹',
        cat_brand_global: '브랜딩',
        cat_nature: '자연',
        cat_pastel: '파스텔',
        cat_neon_modern: '네온/모던',
        cat_earth: '어스 톤',
        cat_monochrome: '모노크롬',
        btn_export_css: 'CSS / Tailwind 내보내기',
        my_palettes_title: '내 보관함',
        search_result_empty: '검색 결과가 없습니다.',
        footer_copy: '© 2024 RGBdom. 디자인을 위한 모든 색상.'
    },
    en: {
        nav_picker: 'Picker',
        nav_library: 'Library',
        nav_today: 'Inspo',
        nav_inspiration: 'Motion',
        nav_guide: 'Guide',
        nav_my: 'My Library',
        detail_mood: 'Mood',
        detail_advice: 'Design Advice',
        detail_usage: 'Usage',
        detail_similar: 'Similar Colors',
        detail_contrast: 'Contrast Test',
        btn_copy_hex: 'Copy HEX',
        btn_copy_rgb: 'Copy RGB',
        btn_reset: 'Reset',
        btn_save: 'Save to My',
        btn_share: 'Share Link',
        btn_close: 'Close',
        search_placeholder: 'Search names or tags...',
        empty_fav: 'Your library is empty.',
        select_family: 'Select Family',
        keyboard_guide_title: 'Controls',
        keyboard_guide_1: 'Click R/G/B: Select Channel',
        keyboard_guide_2: '← →: Fine Adjust Channel',
        keyboard_guide_3: 'Space: Restart Roulette',
        inspiration_subtitle: 'Stop to see palette • Click color to jump to Picker',
        guide_subtitle: 'Basic and practical knowledge of color',
        library_subtitle: 'Color library categorized by usage',
        cat_all: 'All',
        cat_ui_web: 'UI/Web',
        cat_brand_global: 'Branding',
        cat_nature: 'Nature',
        cat_pastel: 'Pastel',
        cat_neon_modern: 'Neon/Modern',
        cat_earth: 'Earth Tone',
        cat_monochrome: 'Monochrome',
        btn_export_css: 'Export CSS / Tailwind',
        my_palettes_title: 'My Palettes',
        search_result_empty: 'No results found.',
        footer_copy: '© 2024 RGBdom. All colors for design.'
    }
};
