// ??? Designer Colors (?⑸룄蹂?遺꾨쪟) ??????????????????????????????????????????
const designerColors = {

    ui_web: [
        { name: '踰꾩? 釉붾（',        hex: '#0070F3' },
        { name: '?깃났 洹몃┛',        hex: '#00C853' },
        { name: '寃쎄퀬 ?곕쾭',        hex: '#FF6F00' },
        { name: '?ㅻ쪟 ?덈뱶',        hex: '#FF1744' },
        { name: '?뺣낫 ??,          hex: '#00BCD4' },
        { name: '留곹겕 釉붾（',        hex: '#1976D2' },
        { name: '鍮꾪솢??洹몃젅??,    hex: '#9E9E9E' },
        { name: '?ㅽ겕 諛곌꼍',        hex: '#121212' },
        { name: '移대뱶 ?붿씠??,      hex: '#FAFAFA' },
        { name: '蹂대뜑 洹몃젅??,      hex: '#E0E0E0' },
        { name: '?ъ빱??釉붾（',      hex: '#2563EB' },
        { name: '??꾩슦 釉붾옓',      hex: '#0F172A' },
    ],

    brand_global: [
        { name: '?좏뵆 ?ㅽ럹?댁뒪洹몃젅??, hex: '#1D1D1F' },
        { name: '援ш? ?덈뱶',           hex: '#EA4335' },
        { name: '?ㅽ룷?고뙆??洹몃┛',     hex: '#1DB954' },
        { name: '?룻뵆由?뒪 ?덈뱶',       hex: '#E50914' },
        { name: '?щ옓 ?쇳뵆',           hex: '#4A154B' },
        { name: '?붿뒪肄붾뱶 釉붾윭??,     hex: '#5865F2' },
        { name: '?좏뒠釉??덈뱶',         hex: '#FF0000' },
        { name: '?몄뒪?洹몃옩 ?쇳뵆',     hex: '#C13584' },
        { name: '硫뷀? 釉붾（',           hex: '#0866FF' },
        { name: '?몄쐞??釉붾（',         hex: '#1DA1F2' },
        { name: '?꾨쭏議??ㅻ젋吏',       hex: '#FF9900' },
        { name: '留덉씠?щ줈?뚰봽??釉붾（', hex: '#0078D4' },
        { name: '?먯꽱??釉붾（',         hex: '#1878F3' },
        { name: '?깊넚 釉붾옓',           hex: '#010101' },
        { name: '留곹겕?쒖씤 釉붾（',       hex: '#0A66C2' },
        { name: '?먯뼱鍮꾩븻鍮??덈뱶',     hex: '#FF5A5F' },
    ],

    nature: [
        { name: '?щ젅?ㅽ듃 洹몃┛',  hex: '#228B22' },
        { name: '?ㅼ뭅??釉붾（',    hex: '#87CEEB' },
        { name: '???ㅼ뀡',        hex: '#006994' },
        { name: '?좎뀑 ?ㅻ젋吏',    hex: '#FF4500' },
        { name: '泥대━ 釉붾씪??,    hex: '#FFB7C5' },
        { name: '怨⑤뱺 ?뚮뱶',      hex: '#C2B280' },
        { name: '紐⑥뒪 洹몃┛',      hex: '#8A9A5B' },
        { name: '?쇰깽???꾨뱶',    hex: '#967BB6' },
        { name: '?ㅻ줈??洹몃┛',    hex: '#00FFCC' },
        { name: '?고샇珥?,         hex: '#FF6B6B' },
        { name: '?щ━?ㅽ깉 ?덉씠??,hex: '#5DADE2' },
        { name: '媛???⑦뭾',      hex: '#D35400' },
        { name: '?덈꼍 ?댁뒳',      hex: '#E8F5E9' },
        { name: '?대컮?쇨린',       hex: '#FFC300' },
        { name: '?대겮 洹몃┛',      hex: '#3D9970' },
    ],

    pastel: [
        { name: '踰좎씠鍮??묓겕',   hex: '#FFD1DC' },
        { name: '?쇰깽??誘몄뒪??, hex: '#E6E6FA' },
        { name: '誘쇳듃 ?щ┝',     hex: '#B5EAD7' },
        { name: '?쇱튂 釉붾윭??,   hex: '#FFCBA4' },
        { name: '踰좎씠鍮?釉붾（',   hex: '#AED6F1' },
        { name: '踰꾪꽣 ?먮줈??,   hex: '#FFF0AA' },
        { name: '?쇱씪??,        hex: '#D7B2FF' },
        { name: '濡쒖쫰 荑쇱툩',     hex: '#F7CAC9' },
        { name: '珥덊겕 ?붿씠??,   hex: '#F5F5F0' },
        { name: '?ㅼ뭅??諛붿씠?щ젢', hex: '#C9B1FF' },
        { name: '?뚯슦??釉붾（',   hex: '#B0E0E6' },
        { name: '?덈땲?',        hex: '#F0FFF0' },
    ],

    neon_modern: [
        { name: '?ㅼ삩 ?묓겕',      hex: '#FF10F0' },
        { name: '?쇰젆?몃┃ 釉붾（',  hex: '#00B4FF' },
        { name: '?ㅼ삩 洹몃┛',      hex: '#39FF14' },
        { name: '?ъ씠踰??먮줈??,  hex: '#FFE600' },
        { name: '???ㅻ젋吏',      hex: '#FF6A00' },
        { name: '留ㅽ듃由?뒪 洹몃┛',  hex: '#00FF41' },
        { name: 'UV ?쇳뵆',        hex: '#7B00FF' },
        { name: '?덉씠? ?덈뱶',    hex: '#FF003F' },
        { name: '?濡쒓렇???쒖븞',  hex: '#00FCCE' },
        { name: '湲由ъ튂 留덉젨?',  hex: '#FF00FF' },
        { name: '?뚮씪利덈쭏 釉붾（',  hex: '#0D00FF' },
        { name: '?덉씠釉??먮줈??,  hex: '#FFFC00' },
    ],

    earth: [
        { name: '?뚮씪肄뷀?',     hex: '#C27A54' },
        { name: '??踰좎씠吏',    hex: '#D2B48C' },
        { name: '?쒖뿉??,       hex: '#A0522D' },
        { name: '移댄궎',         hex: '#C3AA7E' },
        { name: '?대룄鍮??덈뱶',  hex: '#BD5B00' },
        { name: '?명뵾??,       hex: '#704214' },
        { name: '?대젅??,       hex: '#B5651D' },
        { name: '?뚮뱶?ㅽ넠',     hex: '#DEB887' },
        { name: '?ㅽ겕 珥덉퐳??,  hex: '#4E2623' },
        { name: '?щ━釉??쒕옪',  hex: '#6B7C3A' },
        { name: '濡쒖뒪???꾨쾭',  hex: '#8B4513' },
        { name: '怨⑤뱺 ?먮줈??,  hex: '#DAA520' },
    ],

    monochrome: [
        { name: '?⑥뼱 釉붾옓',   hex: '#000000' },
        { name: '由ъ튂 釉붾옓',   hex: '#0A0A0A' },
        { name: '?ㅽ겕 李⑥퐳',   hex: '#212121' },
        { name: '李⑥퐳 洹몃젅??, hex: '#424242' },
        { name: '誘몃뵒??洹몃젅??,hex: '#616161' },
        { name: '?ㅻ쾭',        hex: '#9E9E9E' },
        { name: '?쇱씠??洹몃젅??,hex: '#E0E0E0' },
        { name: '?ㅽ봽 ?붿씠??, hex: '#F5F5F5' },
        { name: '?⑥뼱 ?붿씠??, hex: '#FFFFFF' },
        { name: '?ㅻえ??,      hex: '#738290' },
        { name: '?꾨줈?ㅽ듃',    hex: '#D6E4E9' },
        { name: '?좎떆',        hex: '#B2BEC3' },
    ],

};

// ??? Color Name References (媛?섎떎 ??+ ?곷Ц) ????????????????????????????????
const colorNameReferences = {
    '媛???⑦뭾':    { hex: '#D35400', tags: ['autumn', '?ㅻ젋吏', '遺됱?'] },
    '媛먯껌??:       { hex: '#1428A0', tags: ['business', '?꾨Ц', '?뚮옉'] },
    '寃??:         { hex: '#000000', tags: ['contrast', '?곗븘', '?대몺'] },
    '怨⑤뱶':         { hex: '#FFD700', tags: ['premium', '?붾젮', '??뀛由?] },
    '湲덉깋':         { hex: '#FFD700', tags: ['湲?, '怨좉툒', '?⑷툑'] },
    '?뱀깋':         { hex: '#00B050', tags: ['natural', '?깆옣', '?먯뿰'] },
    '?ㅼ씠鍮?:       { hex: '#001F5B', tags: ['formal', '?대옒??, '?좊ː'] },
    '?ㅼ삩 洹몃┛':    { hex: '#39FF14', tags: ['neon', '?뺢킅', '諛앹?'] },
    '?ㅼ삩 ?묓겕':    { hex: '#FF10F0', tags: ['neon', '?뺢킅', '?묓겕'] },
    '?몃옉':         { hex: '#FFD700', tags: ['bright', '?먮꼫吏', '寃쎄퀬'] },
    '?ㅽ겕洹몃┛':     { hex: '#006400', tags: ['dark', '?대몢??, '珥덈줉'] },
    '?쇰깽??:       { hex: '#967BB6', tags: ['soft', '?곗븘', '蹂대씪'] },
    '?쇱엫':         { hex: '#32CD32', tags: ['fresh', '?앷린', '諛앹?'] },
    '猷⑤퉬':         { hex: '#9B111E', tags: ['jewel', '蹂댁꽍', '鍮④컯'] },
    '留덈，':         { hex: '#800000', tags: ['dark', '媛뺥븿', '?대옒??] },
    '留덉젨?':       { hex: '#FF00FF', tags: ['vibrant', '?ㅼ삩', '媛뺣젹'] },
    '誘쇳듃':         { hex: '#00B8A9', tags: ['fresh', '李⑤텇', '?먯뿰'] },
    '踰꾧굔??:       { hex: '#800020', tags: ['luxury', '???, '鍮④컯'] },
    '踰좎씠吏':       { hex: '#C8A882', tags: ['elegant', '?꾪넻', '?곕쑜??] },
    '蹂대씪':         { hex: '#7851A9', tags: ['luxury', '李쎌쓽', '?곗븘'] },
    '遺꾪솉':         { hex: '#FF69B4', tags: ['pink', '洹?ъ?', '遺?쒕윭?'] },
    '鍮④컯':         { hex: '#FF0000', tags: ['primary', '媛뺣젹', '?꾪뿕'] },
    '?대が':         { hex: '#FA8072', tags: ['warm', '?뚰봽??, '?묓겕'] },
    '?ㅼ뭅?대툝猷?:   { hex: '#87CEEB', tags: ['sky', '?섎뒛', '留묒쓬'] },
    '?쒖븞':         { hex: '#00BCD4', tags: ['tech', '?곸떊', '泥?웾'] },
    '?꾩씠蹂대━':     { hex: '#FFFFF0', tags: ['warm', '遺?쒕윭??, '?붿씠??] },
    '?먮찓?꾨뱶':     { hex: '#50C878', tags: ['jewel', '蹂댁꽍', '珥덈줉'] },
    '?ㅻ젋吏':       { hex: '#FF6B00', tags: ['energy', '?쒕룞', '?곕쑜??] },
    '?щ━釉?:       { hex: '#808000', tags: ['earthy', '?먯뿰', '援곕?'] },
    '?몃뵒怨?:       { hex: '#4B0082', tags: ['deep', '?좊퉬', '?대몢??] },
    '泥?줉':         { hex: '#20B2AA', tags: ['cool', '?몄븞', '諛붾떎'] },
    '肄붾엫':         { hex: '#FF7F50', tags: ['vibrant', '?쒓린', '?щ쫫'] },
    '肄붾컻??:       { hex: '#0047AB', tags: ['deep', '吏꾪븳?뚮옉', '媛뺣젹'] },
    '?щ┝??:       { hex: '#DC143C', tags: ['intense', '吏꾪븳鍮④컯', '?댁젙'] },
    '?곗쉼?댁쫰':     { hex: '#40E0D0', tags: ['tropical', '?닿뎅??, '?쒖썝'] },
    '?뚮씪肄뷀?':     { hex: '#C27A54', tags: ['warm', '?숈깋', '鍮덊떚吏'] },
    '?뚮옉':         { hex: '#0099FF', tags: ['cool', '?좊ː', '?섎뒛'] },
    '?쇳뵆':         { hex: '#6A0DAD', tags: ['purple', '蹂대씪', '李쎌쓽'] },
    '?섎━?숉겢':     { hex: '#CCCCFF', tags: ['soft', '?뚯뒪??, '?고븳'] },
    '?щ젅?ㅽ듃洹몃┛': { hex: '#228B22', tags: ['forest', '??, '?먯뿰'] },
    '?묓겕':         { hex: '#FF6B9D', tags: ['modern', '?ъ꽦', '遺?쒕윭?'] },
    '?섎뒛??:       { hex: '#87CEEB', tags: ['sky', '?섎뒛', '留묒쓬'] },
    '?닿뎔??:       { hex: '#000080', tags: ['formal', '?대옒??, '?좊ː'] },
    '?ロ븨??:       { hex: '#FF69B4', tags: ['hot', '媛뺣젹', '?묓겕'] },
    '?뚯깋':         { hex: '#808080', tags: ['neutral', '以묐┰', '李⑤텇'] },
    '?곗깋':         { hex: '#FFFFFF', tags: ['clean', '怨듦컙', '?쒖닔'] },
    '梨좎퐳':         { hex: '#36454F', tags: ['dark', '?대몢??, '以묒꽦'] },
    '?щ젅?댄듃':     { hex: '#708090', tags: ['neutral', '?뚯깋', '李⑤텇'] },
    '???:         { hex: '#C0C0C0', tags: ['modern', '?몃젴', '湲덉냽'] },
    '?щ씪?꾪듃':     { hex: '#B5651D', tags: ['craft', '?섎Т', '泥쒖뿰'] },
    '?ы뙆?댁뼱':     { hex: '#0F52BA', tags: ['jewel', '蹂댁꽍', '?뚮옉'] },
    '?덈땲':         { hex: '#FFC300', tags: ['warm', '轅', '?몃옉'] },
    '癒몄뒪???:     { hex: '#FFDB58', tags: ['warm', '鍮덊떚吏', '?몃옉'] },
    '?쇱튂':         { hex: '#FFCBA4', tags: ['soft', '蹂듭댂??, '?뚯뒪??] },
    '由대씫':         { hex: '#D7B2FF', tags: ['soft', '?곕낫??, '?뚯뒪??] },
};

// ??? Design Inspiration Palettes ????????????????????????????????????????????
const designInspiration = [
    { name: '誘몃땲硫 紐⑤뜕', name_en: 'Minimal Modern', colors: ['#000000', '#FFFFFF', '#8B8B8B', '#E8E8E8'] },
    { name: '?ㅼ삩 ?섏씠??, name_en: 'Neon Night', colors: ['#FF10F0', '#FFE600', '#00B4FF', '#7B00FF'] },
    { name: '?댁뼇 ?닿?', name_en: 'Ocean Vacation', colors: ['#005377', '#00A8E8', '#00D9FF', '#B5EAD7'] },
    { name: '?쒕줈???쇰ぐ', name_en: 'Deep Sunset', colors: ['#FF6B35', '#FFB627', '#C27A54', '#4E2623'] },
    { name: '?뀁쓽 轅?, name_en: 'Forest Dream', colors: ['#228B22', '#8A9A5B', '#DEB887', '#006994'] },
    { name: '由ы대뱶 湲?섏뒪', name_en: 'Liquid Glass', colors: ['#E0F7FF', '#AED6F1', '#5DADE2', '#1A5276'] },
    { name: '?ㅽ겕 ?섎━嫄댁뒪', name_en: 'Dark Elegance', colors: ['#000000', '#212121', '#424242', '#9E9E9E'] },
    { name: '肄붾엫 ?좎뀑', name_en: 'Coral Sunset', colors: ['#FF7F50', '#FF6B9D', '#FFD1DC', '#FFCBA4'] },
    { name: '?대컲 ?뚰겕', name_en: 'Urban Tech', colors: ['#0070F3', '#212121', '#E0E0E0', '#FAFAFA'] },
    { name: '?뚯뒪???쒕┝', name_en: 'Pastel Dream', colors: ['#FFD1DC', '#B5EAD7', '#AED6F1', '#FFF0AA'] },
    { name: '釉뚮옖???뚯썙', name_en: 'Brand Power', colors: ['#E50914', '#1DB954', '#5865F2', '#FF9900'] },
    { name: '?댁뒪 ??, name_en: 'Earth Tone', colors: ['#C27A54', '#A0522D', '#DEB887', '#6B7C3A'] },
];

// ??? Today\'s Design Pick (Cards) ????????????????????????????????????????????
const designCards = [
    {
        id: '01',
        name: 'Night 횞 Kiwi',
        category: '?ㅽ룷痢좎썾??/ ?뚰겕 / ?ㅽ듃由?釉뚮옖??,
        category_en: 'Sportswear / Tech / Street Branding',
        description: '?대몺???リ퀬 ?섏삤???뺢킅???鍮?n媛뺥븳 湲댁옣媛먭낵 ?딆? ?먮꼫吏瑜??숈떆??留뚮벊?덈떎.',
        description_en: 'Fluorescent contrast emerging from darkness\nCreates strong tension and youthful energy simultaneously.',
        colors: [{ name: 'Night', hex: '#222222' }, { name: 'Kiwi', hex: '#89E900' }],
    },
    {
        id: '02',
        name: 'Cloud 횞 Blue',
        category: 'IT / ??뚰겕 / 紐⑤뜕 釉뚮옖??,
        category_en: 'IT / Fintech / Modern Branding',
        description: '源⑤걮???щ갚 ?꾩뿉 ?곹엺 ?좊챸???좊ː\n李④컩吏 ?딆쑝硫댁꽌 ?꾨Ц?깆쓣 ?꾨떖?⑸땲??',
        description_en: 'Vivid trust written on clean space\nConveys professionalism without being cold.',
        colors: [{ name: 'Canvas Cloud', hex: '#EDF1F5' }, { name: 'Electric Blue', hex: '#0145F2' }],
    },
    {
        id: '03',
        name: 'Night 횞 Imperial',
        category: '??뀛由?釉뚮옖??/ ?꾨━誘몄뾼 ?⑦궎吏 / ?쒕꽕留덊떛',
        category_en: 'Luxury Branding / Premium Package / Cinematic',
        description: '?대몺 ?띿뿉???쇱뼱?ㅻⅤ??遺됱? 湲고뭹\n?쒖꽑????踰덉뿉 ?щ줈?≪쑝硫댁꽌??臾닿쾶媛먯쓣 ?껋? ?딆뒿?덈떎.',
        description_en: 'Red elegance rising in the darkness\nCaptures attention while maintaining weight.',
        colors: [{ name: 'Night', hex: '#000F08' }, { name: 'Imperial', hex: '#FB3640' }],
    },
    {
        id: '04',
        name: 'ICE 횞 MINT',
        category: '移댄럹 / 酉고떚 / ?곕땲??釉뚮옖??,
        category_en: 'Cafe / Beauty / Wellness Branding',
        description: '?쒖닔???곗쑀鍮??꾩뿉 ?뱁엺 ?곹겮??誘쇳듃\n遺?쒕윭?곕㈃?쒕룄 ?쒕졆???몄긽???④퉩?덈떎.',
        description_en: 'Fresh mint on top of pure milky white\nLeaves a soft yet distinct impression.',
        colors: [{ name: 'Ice Latte', hex: '#E4DDD3' }, { name: 'The Mint', hex: '#00A19B' }],
    },
    {
        id: '05',
        name: 'Wattle 횞 Bottle Green',
        category: '?ㅺ????몃뱶 / 移쒗솚寃?釉뚮옖??/ ?꾩썐?꾩뼱',
        category_en: 'Organic Food / Eco-friendly / Outdoor',
        description: '?뀁쓽 源딆씠? ?뉗궡???앷린媛 留뚮굹???먮━\n?먯뿰二쇱쓽 ?띿뿉?쒕룄 ?덉뿉 ?꾨뒗 ?앸룞媛먯쓣 留뚮벊?덈떎.',
        description_en: 'Where forest depth meets sunlight vitality\nCreates striking vividness within naturalism.',
        colors: [{ name: 'Wattle', hex: '#CCDA47' }, { name: 'Bottle Green', hex: '#0A3625' }],
    },
    {
        id: '06',
        name: 'Sand 횞 Rust',
        category: '?명뀒由ъ뼱 / ?덈━鍮?/ 鍮덊떚吏 釉뚮옖??,
        category_en: 'Interior / Home Living / Vintage Branding',
        description: '?щ쭑???곕쑜??紐⑤옒 ?꾩뿉 ?뱁엺 ?뱀뒯 遺됱쓬\n?ㅻ옒??寃껊뱾??媛吏?怨좎슂???꾨쫫?ㅼ?.',
        description_en: 'Rusted red on top of warm desert sand\nThe quiet beauty of old things.',
        colors: [{ name: 'Sand', hex: '#E8D5B7' }, { name: 'Rust', hex: '#B7410E' }],
    },
    {
        id: '07',
        name: 'Ink 횞 Gold',
        category: '異쒗뙋 / 由ы뀒??/ ?섏씠?붾뱶 釉뚮옖??,
        category_en: 'Publishing / Retail / High-end Branding',
        description: '源딆? 癒밸튆 ?꾩뿉 鍮쏅굹???⑷툑???鍮?n怨좎쟾?곸씠硫댁꽌???꾨??곸씤 ?덇꺽???댁뒿?덈떎.',
        description_en: 'Brilliant gold contrast on deep ink\nEmbodies both classical and modern elegance.',
        colors: [{ name: 'Ink', hex: '#1A1A2E' }, { name: 'Gold', hex: '#D4AF37' }],
    },
    {
        id: '08',
        name: 'Blush 횞 Slate',
        category: '?⑥뀡 / ?⑤뵫 / ?쇱씠?꾩뒪???釉뚮옖??,
        category_en: 'Fashion / Wedding / Lifestyle Branding',
        description: '遺?쒕윭???λ컠鍮쏄낵 李④????щ젅?댄듃??洹좏삎\n媛먯꽦?곸씠硫댁꽌???몃젴???몄긽???꾨떖?⑸땲??',
        description_en: 'Balance of soft blush and cold slate\nConveys an emotional yet sophisticated impression.',
        colors: [{ name: 'Blush', hex: '#F4A7B9' }, { name: 'Slate', hex: '#475569' }],
    },
    {
        id: '09',
        name: 'Void 횞 Neon',
        category: '寃뚯엫 / ?뚯븙 / ?ㅽ듃由щ컢 釉뚮옖??,
        description: '?꾩쟾???대몺 ?띿뿉???곗졇 ?섏삤???뺢킅\n媛뺣??섍퀬 誘몃옒?곸씤 ?먮꼫吏瑜??쒗쁽?⑸땲??',
        colors: [{ name: 'Void', hex: '#0D0D0D' }, { name: 'Neon', hex: '#FF10F0' }],
    },
    {
        id: '10',
        name: 'Coral 횞 Midnight',
        category: '?뷀꽣?뚯씤癒쇳듃 / K-??/ ?곸긽 釉뚮옖??,
        description: '?앸룞媛??섏튂??肄붾엫怨?源딆? 誘몃뱶?섏옃???鍮?n?앺븯硫댁꽌??臾닿쾶媛??덈뒗 釉뚮옖?쒕? 留뚮벊?덈떎.',
        colors: [{ name: 'Coral', hex: '#FF6B6B' }, { name: 'Midnight', hex: '#191970' }],
    },
    {
        id: '11',
        name: 'Cream 횞 Forest',
        category: '?ㅺ???釉뚮옖??/ 移댄럹 / ?띿궛臾?,
        description: '?щ━誘명븳 諛뷀깢???뀁쓽 源딆씠媛 ?뷀빐吏?議고솕\n?먯뿰?ㅻ읇怨?嫄닿컯???대?吏瑜?留뚮벊?덈떎.',
        colors: [{ name: 'Cream', hex: '#FFF8DC' }, { name: 'Forest', hex: '#2D5A27' }],
    },
    {
        id: '12',
        name: 'Denim 횞 Wheat',
        category: '罹먯＜???⑥뀡 / ?꾩썐?꾩뼱 ?쇱씠??,
        description: '?뚰겕?⑥뼱??寃ш퀬?④낵 諛諛?쓽 ?곕쑜??n?쇱긽 ??吏꾩젙???덈뒗 ?ㅽ??쇱쓣 ?쒗쁽?⑸땲??',
        colors: [{ name: 'Denim', hex: '#1560BD' }, { name: 'Wheat', hex: '#F5DEB3' }],
    },
];

// ??? Color Distance (similar color search) ??????????????????????????????????
function findSimilarColors(r, g, b, count = 8) {
    const distances = [];
    for (const [name, color] of Object.entries(colorNameReferences)) {
        const rgb = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(color.hex);
        if (rgb) {
            const cr = parseInt(rgb[1], 16);
            const cg = parseInt(rgb[2], 16);
            const cb = parseInt(rgb[3], 16);
            const distance = Math.sqrt((cr - r) ** 2 + (cg - g) ** 2 + (cb - b) ** 2);
            distances.push({ name, hex: color.hex, distance });
        }
    }
    return distances.sort((a, b) => a.distance - b.distance).slice(0, count);
}

// ??? Design Guides ??????????????????????????????????????????
const designGuides = [
    { title: '蹂댁깋 ?鍮?(Complementary)', desc: '?됱긽?섏뿉???쒕줈 留덉＜ 蹂대뒗 ???됱긽??議고빀?섎뒗 諛⑹떇?낅땲?? 媛뺥븳 ?ㅽ룷?몃씪?댄듃? ?앸룞媛먯쓣 二쇱뼱 以묒슂??踰꾪듉?대굹 媛뺤“ 遺遺꾩뿉 ?곹빀?⑸땲??', colors: ['#FF3B30', '#34C759'] },
    { title: '?좎궗??(Analogous)', desc: '?됱긽?섏뿉???쒕줈 ?몄젒??3?됱쓣 ?ъ슜?⑸땲?? ?덉씠 ?몄븞?섍퀬 議고솕濡쒖슦硫? ?먯뿰?대굹 ?됱삩???뚮쭏瑜??쒗쁽????二쇰줈 ?ъ슜?⑸땲??', colors: ['#007AFF', '#5856D6', '#AF52DE'] },
    { title: '?ㅼ삩??(Tone-on-Tone)', desc: '?숈씪???됱긽?먯꽌 梨꾨룄? 紐낅룄留??ㅻⅤ寃?議고빀?섎뒗 諛곗튂?낅땲?? 援됱옣???덉젙?곸씠怨?源붾걫?섎ŉ ?쇨????덈뒗 釉뚮옖???대?吏瑜?留뚮벊?덈떎.', colors: ['#0A84FF', '#64D2FF', '#B0E2FF'] },
    { title: '60-30-10 洹쒖튃', desc: '媛??留롮씠 ?곗씠??UI 而щ윭 鍮꾩쑉?낅땲?? 60%??諛곌꼍(二쇱“??, 30%??蹂댁“?? ?섎㉧吏 10%??媛뺤“(Accent)?됱쑝濡?諛곕텇?섏뿬 ?덉젙媛먯쓣 以띾땲??', colors: ['#F5F5F7', '#D1D1D6', '#FF9500'] },
    { title: '紐⑤끂?щ＼ (Monochrome)', desc: '?섎굹???됱긽??踰좎씠?ㅻ줈 ?먭퀬 寃?? ?곗깋, ?뚯깋???욎뼱 紐낅룄瑜?議곗젅?⑸땲?? 洹밴컯???ы뵆?④낵 紐⑤뜕?⑥쓣 二쇨린 醫뗭? 臾댁콈??諛곗뿴?낅땲??', colors: ['#111111', '#888888', '#EEEEEE'] }
];
// ?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧??//  Translations (I18n)
// ?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧?먥븧??
const uiTranslations = {
    kr: {
        nav_picker: '而щ윭 ?쇱빱',
        nav_library: '?쇱씠釉뚮윭由?,
        nav_today: '?ㅻ뒛???곴컧',
        nav_inspiration: '?몄뒪?쇰젅?댁뀡',
        nav_guide: '媛?대뱶',
        nav_my: '??蹂닿???,
        detail_mood: '?됱긽 ?깃꺽',
        detail_advice: '?붿옄??議곗뼵',
        detail_usage: '?쒖슜 遺꾩빞',
        detail_similar: '?좎궗???됱긽 異붿쿇',
        detail_contrast: '?띿뒪??媛?낆꽦 ?뚯뒪??,
        btn_copy_hex: 'HEX 蹂듭궗',
        btn_copy_rgb: 'RGB 蹂듭궗',
        btn_reset: '由ъ뀑',
        btn_save: '蹂닿??⑥뿉 ???,
        btn_share: '怨듭쑀?섍린',
        btn_close: '?リ린',
        search_placeholder: '?됱긽 ?대쫫?대굹 ?쒓렇 寃??..',
        empty_fav: '蹂닿??⑥씠 鍮꾩뼱?덉뒿?덈떎.',
        select_family: '??怨꾩뿴 ?좏깮',
        keyboard_guide_title: '議곗옉 諛⑸쾿',
        keyboard_guide_1: 'R / G / B ?대┃: 梨꾨꼸 ?좏깮',
        keyboard_guide_2: '???? ?좏깮 梨꾨꼸 誘몄꽭 議곗젙',
        keyboard_guide_3: '?ㅽ럹?댁뒪諛? 猷곕젢 ?ъ떆??,
        inspiration_subtitle: '硫덉텛硫??붾젅?멸? ?섑??⑸땲?????됱쓣 ?대┃?섎㈃ Color Picker濡??대룞',
        guide_subtitle: '?됱쓣 ?ㅻ（??湲곕낯?곸씠怨??ㅼ슜?곸씤 吏?앸뱾',
        library_subtitle: '?⑸룄蹂꾨줈 遺꾨쪟??而щ윭 ?쇱씠釉뚮윭由?,
        cat_all: '?꾩껜蹂닿린',
        cat_ui_web: 'UI/??,
        cat_brand_global: '釉뚮옖??,
        cat_nature: '?먯뿰/?댁뒪',
        cat_pastel: '媛먯꽦/?뚯뒪??,
        cat_neon_modern: '?ㅼ삩/紐⑤뜕',
        cat_earth: '?댁뒪 ??,
        cat_monochrome: '紐⑤끂?щ＼',
        footer_copy: '짤 2024 RGBdom. ?붿옄?몄쓣 ?꾪븳 紐⑤뱺 ?됱긽.'
    },
    en: {
        nav_picker: 'Picker',
        nav_library: 'Library',
        nav_today: 'Inspo',
        nav_inspiration: 'Motion',
        nav_guide: 'Guide',
        nav_my: 'My Library',
        detail_mood: 'Mood',
        detail_advice: 'Design Advice',
        detail_usage: 'Usage',
        detail_similar: 'Similar Colors',
        detail_contrast: 'Contrast Test',
        btn_copy_hex: 'Copy HEX',
        btn_copy_rgb: 'Copy RGB',
        btn_reset: 'Reset',
        btn_save: 'Save to My',
        btn_share: 'Share Link',
        btn_close: 'Close',
        search_placeholder: 'Search names or tags...',
        empty_fav: 'Your library is empty.',
        select_family: 'Select Family',
        keyboard_guide_title: 'Controls',
        keyboard_guide_1: 'Click R/G/B: Select Channel',
        keyboard_guide_2: '???? Fine Adjust Channel',
        keyboard_guide_3: 'Space: Restart Roulette',
        inspiration_subtitle: 'Stop to see palette ??Click color to jump to Picker',
        guide_subtitle: 'Basic and practical knowledge of color',
        library_subtitle: 'Color library categorized by usage',
        cat_all: 'All',
        cat_ui_web: 'UI/Web',
        cat_brand_global: 'Branding',
        cat_nature: 'Nature',
        cat_pastel: 'Pastel',
        cat_neon_modern: 'Neon/Modern',
        cat_earth: 'Earth Tone',
        cat_monochrome: 'Monochrome',
        footer_copy: '짤 2024 RGBdom. All colors for design.'
    }
};
