// ─── Designer Colors (용도별 분류) ──────────────────────────────────────────
const designerColors = {
    ui_web: [
        { name: '버셀 블루', name_en: 'Vercel Blue', hex: '#0070F3' },
        { name: '성공 그린', name_en: 'Success Green', hex: '#00C853' },
        { name: '경고 앰버', name_en: 'Warning Amber', hex: '#FF6F00' },
        { name: '오류 레드', name_en: 'Error Red', hex: '#FF1744' },
        { name: '정보 틸', name_en: 'Info Teal', hex: '#00BCD4' },
        { name: '링크 블루', name_en: 'Link Blue', hex: '#1976D2' },
        { name: '비활성 그레이', name_en: 'Inactive Gray', hex: '#9E9E9E' },
        { name: '다크 배경', name_en: 'Dark Background', hex: '#121212' },
        { name: '카드 화이트', name_en: 'Card White', hex: '#FAFAFA' },
        { name: '보더 그레이', name_en: 'Border Gray', hex: '#E0E0E0' },
        { name: '포커스 블루', name_en: 'Focus Blue', hex: '#2563EB' },
        { name: '섀도우 블랙', name_en: 'Shadow Black', hex: '#0F172A' },
    ],
    brand_global: [
        { name: '애플 스페이스그레이', name_en: 'Apple SpaceGray', hex: '#1D1D1F' },
        { name: '구글 레드', name_en: 'Google Red', hex: '#EA4335' },
        { name: '스포티파이 그린', name_en: 'Spotify Green', hex: '#1DB954' },
        { name: '넷플릭스 레드', name_en: 'Netflix Red', hex: '#E50914' },
        { name: '슬랙 퍼플', name_en: 'Slack Purple', hex: '#4A154B' },
        { name: '디스코드 블러플', name_en: 'Discord Blurple', hex: '#5865F2' },
        { name: '유튜브 레드', name_en: 'Youtube Red', hex: '#FF0000' },
        { name: '인스타그램 퍼플', name_en: 'Instagram Purple', hex: '#C13584' },
        { name: '메타 블루', name_en: 'Meta Blue', hex: '#0866FF' },
        { name: '트위터 블루', name_en: 'Twitter Blue', hex: '#1DA1F2' },
        { name: '아마존 오렌지', name_en: 'Amazon Orange', hex: '#FF9900' },
        { name: '마이크로소프트 블루', name_en: 'MS Blue', hex: '#0078D4' },
        { name: '텐센트 블루', name_en: 'Tencent Blue', hex: '#1878F3' },
        { name: '틱톡 블랙', name_en: 'Tiktok Black', hex: '#010101' },
        { name: '링크드인 블루', name_en: 'LinkedIn Blue', hex: '#0A66C2' },
        { name: '에어비앤비 레드', name_en: 'Airbnb Red', hex: '#FF5A5F' },
    ],
    nature: [
        { name: '포레스트 그린', name_en: 'Forest Green', hex: '#228B22' },
        { name: '스카이 블루', name_en: 'Sky Blue', hex: '#87CEEB' },
        { name: '딥 오션', name_en: 'Deep Ocean', hex: '#006994' },
        { name: '선셋 오렌지', name_en: 'Sunset Orange', hex: '#FF4500' },
        { name: '체리 블라썸', name_en: 'Cherry Blossom', hex: '#FFB7C5' },
        { name: '골든 샌드', name_en: 'Golden Sand', hex: '#C2B280' },
        { name: '모스 그린', name_en: 'Moss Green', hex: '#8A9A5B' },
        { name: '라벤더 필드', name_en: 'Lavender Field', hex: '#967BB6' },
        { name: '오로라 그린', name_en: 'Aurora Green', hex: '#00FFCC' },
        { name: '산호초', name_en: 'Coral Reef', hex: '#FF6B6B' },
        { name: '크리스탈 레이크', name_en: 'Crystal Lake', hex: '#5DADE2' },
        { name: '가을 단풍', name_en: 'Autumn Leaf', hex: '#D35400' },
    ],
    pastel: [
        { name: '베이비 핑크', name_en: 'Baby Pink', hex: '#FFD1DC' },
        { name: '라벤더 미스트', name_en: 'Lavender Mist', hex: '#E6E6FA' },
        { name: '민트 크림', name_en: 'Mint Cream', hex: '#B5EAD7' },
        { name: '피치 블러쉬', name_en: 'Peach Blush', hex: '#FFCBA4' },
        { name: '베이비 블루', name_en: 'Baby Blue', hex: '#AED6F1' },
        { name: '버터 옐로우', name_en: 'Butter Yellow', hex: '#FFF0AA' },
        { name: '라일락', name_en: 'Lilac', hex: '#D7B2FF' },
    ],
    neon_modern: [
        { name: '네온 핑크', name_en: 'Neon Pink', hex: '#FF10F0' },
        { name: '일렉트릭 블루', name_en: 'Electric Blue', hex: '#00B4FF' },
        { name: '네온 그린', name_en: 'Neon Green', hex: '#39FF14' },
        { name: '사이버 옐로우', name_en: 'Cyber Yellow', hex: '#FFE600' },
        { name: '핫 오렌지', name_en: 'Hot Orange', hex: '#FF6A00' },
        { name: '매트릭스 그린', name_en: 'Matrix Green', hex: '#00FF41' },
        { name: 'UV 퍼플', name_en: 'UV Purple', hex: '#7B00FF' },
        { name: '레이저 레드', name_en: 'Laser Red', hex: '#FF003F' },
    ],
    earth: [
        { name: '테라코타', name_en: 'Terracotta', hex: '#C27A54' },
        { name: '탄 베이지', name_en: 'Tan Beige', hex: '#D2B48C' },
        { name: '시에나', name_en: 'Sienna', hex: '#A0522D' },
        { name: '카키', name_en: 'Khaki', hex: '#C3AA7E' },
        { name: '샌드스톤', name_en: 'Sandstone', hex: '#DEB887' },
        { name: '다크 초콜렛', name_en: 'Dark Chocolate', hex: '#4E2623' },
        { name: '올리브 드랩', name_en: 'Olive Drab', hex: '#6B7C3A' },
    ],
    monochrome: [
        { name: '퓨어 블랙', name_en: 'Pure Black', hex: '#000000' },
        { name: '다크 차콜', name_en: 'Dark Charcoal', hex: '#212121' },
        { name: '차콜 그레이', name_en: 'Charcoal Gray', hex: '#424242' },
        { name: '미디엄 그레이', name_en: 'Medium Gray', hex: '#616161' },
        { name: '실버', name_en: 'Silver', hex: '#9E9E9E' },
        { name: '라이트 그레이', name_en: 'Light Gray', hex: '#E0E0E0' },
        { name: '퓨어 화이트', name_en: 'Pure White', hex: '#FFFFFF' },
    ]
};

const colorNameReferences = {
    '가을 단풍': { hex: '#D35400', name_en: 'Autumn Leaf', tags: ['autumn', '오렌지', '붉은'] },
    '감청색': { hex: '#1428A0', name_en: 'Royal Blue', tags: ['business', '전문', '파랑'] },
    '검정': { hex: '#000000', name_en: 'Black', tags: ['contrast', '우아', '어둠'] },
    '골드': { hex: '#FFD700', name_en: 'Gold', tags: ['premium', '화려', '럭셔리'] },
    '녹색': { hex: '#00B050', name_en: 'Green', tags: ['natural', '성장', '자연'] },
    '네이비': { hex: '#001F5B', name_en: 'Navy', tags: ['formal', '클래식', '신뢰'] },
    '네온 그린': { hex: '#39FF14', name_en: 'Neon Green', tags: ['neon', '형광', '밝은'] },
    '라벤더': { hex: '#967BB6', name_en: 'Lavender', tags: ['soft', '우아', '보라'] },
    '민트': { hex: '#00B8A9', name_en: 'Mint', tags: ['fresh', '차분', '자연'] },
    '베이지': { hex: '#C8A882', name_en: 'Beige', tags: ['elegant', '전통', '따뜻함'] },
    '보라': { hex: '#7851A9', name_en: 'Purple', tags: ['luxury', '창의', '우아'] },
    '분홍': { hex: '#FF69B4', name_en: 'Pink', tags: ['pink', '귀여움', '부드러움'] },
    '빨강': { hex: '#FF0000', name_en: 'Red', tags: ['primary', '강렬', '위험'] },
    '살몬': { hex: '#FA8072', name_en: 'Salmon', tags: ['warm', '소프트', '핑크'] },
    '스카이블루': { hex: '#87CEEB', name_en: 'Sky Blue', tags: ['sky', '하늘', '맑음'] },
    '시안': { hex: '#00BCD4', name_en: 'Cyan', tags: ['tech', '혁신', '청량'] },
    '아이보리': { hex: '#FFFFF0', name_en: 'Ivory', tags: ['warm', '부드러운', '화이트'] },
    '오렌지': { hex: '#FF6B00', name_en: 'Orange', tags: ['energy', '활동', '따뜻함'] },
    '청록': { hex: '#20B2AA', name_en: 'Teal', tags: ['cool', '편안', '바다'] },
    '회색': { hex: '#808080', name_en: 'Gray', tags: ['neutral', '중립', '차분'] },
    '흰색': { hex: '#FFFFFF', name_en: 'White', tags: ['clean', '공간', '순수'] },
};

const designInspiration = [
    { name: '미니멀 모던', name_en: 'Minimal Modern', colors: ['#000000', '#FFFFFF', '#8B8B8B', '#E8E8E8'] },
    { name: '네온 나이트', name_en: 'Neon Night', colors: ['#FF10F0', '#FFE600', '#00B4FF', '#7B00FF'] },
    { name: '해양 휴가', name_en: 'Ocean Vacation', colors: ['#005377', '#00A8E8', '#00D9FF', '#B5EAD7'] },
    { name: '서로운 일몰', name_en: 'Deep Sunset', colors: ['#FF6B35', '#FFB627', '#C27A54', '#4E2623'] },
    { name: '숲의 꿈', name_en: 'Forest Dream', colors: ['#228B22', '#8A9A5B', '#DEB887', '#006994'] },
    { name: '리퀴드 글래스', name_en: 'Liquid Glass', colors: ['#E0F7FF', '#AED6F1', '#5DADE2', '#1A5276'] },
    { name: '다크 엘리건스', name_en: 'Dark Elegance', colors: ['#000000', '#212121', '#424242', '#9E9E9E'] },
    { name: '코랄 선셋', name_en: 'Coral Sunset', colors: ['#FF7F50', '#FF6B9D', '#FFD1DC', '#FFCBA4'] },
    { name: '어반 테크', name_en: 'Urban Tech', colors: ['#0070F3', '#212121', '#E0E0E0', '#FAFAFA'] },
    { name: '파스텔 드림', name_en: 'Pastel Dream', colors: ['#FFD1DC', '#B5EAD7', '#AED6F1', '#FFF0AA'] },
    { name: '브랜드 파워', name_en: 'Brand Power', colors: ['#E50914', '#1DB954', '#5865F2', '#FF9900'] },
    { name: '어스 톤', name_en: 'Earth Tone', colors: ['#C27A54', '#A0522D', '#DEB887', '#6B7C3A'] },
];

const designCards = [
    {
        id: '01',
        name: 'Night × Kiwi',
        category: '스포츠웨어 / 테크 / 스트릿 브랜딩',
        category_en: 'Sportswear / Tech / Street Branding',
        description: '어둠을 뚫고 나오는 형광의 대비\n강한 긴장감과 젊은 에너지를 동시에 만듭니다.',
        description_en: 'Fluorescent contrast emerging from darkness\nCreates strong tension and youthful energy simultaneously.',
        colors: [{ name: 'Night', hex: '#222222' }, { name: 'Kiwi', hex: '#89E900' }],
    },
    {
        id: '02',
        name: 'Cloud × Blue',
        category: 'IT / 핀테크 / 모던 브랜딩',
        category_en: 'IT / Fintech / Modern Branding',
        description: '깨끗한 여백 위에 적힌 투명한 신뢰\n차갑지 않으면서 전문성을 전달합니다.',
        description_en: 'Vivid trust written on clean space\nConveys professionalism without being cold.',
        colors: [{ name: 'Canvas Cloud', hex: '#EDF1F5' }, { name: 'Electric Blue', hex: '#0145F2' }],
    },
    {
        id: '03',
        name: 'Night × Imperial',
        category: '럭셔리 브랜딩 / 프리미엄 패키지 / 시네마틱',
        category_en: 'Luxury Branding / Premium Package / Cinematic',
        description: '어둠 속에서 피어오르는 붉은 기품\n시선을 단번에 사로잡으면서도 무게감을 잃지 않습니다.',
        description_en: 'Red elegance rising in the darkness\nCaptures attention while maintaining weight.',
        colors: [{ name: 'Night', hex: '#000F08' }, { name: 'Imperial', hex: '#FB3640' }],
    },
    {
        id: '04',
        name: 'ICE × MINT',
        category: '카페 / 뷰티 / 웰니스 브랜딩',
        category_en: 'Cafe / Beauty / Wellness Branding',
        description: '순수한 우유빛 위에 얹힌 상큼한 민트\n부드러우면서도 선명한 인상을 남깁니다.',
        description_en: 'Fresh mint on top of pure milky white\nLeaves a soft yet distinct impression.',
        colors: [{ name: 'Ice Latte', hex: '#E4DDD3' }, { name: 'The Mint', hex: '#00A19B' }],
    },
    {
        id: '05',
        name: 'Wattle × Bottle Green',
        category: '유기농 푸드 / 친환경 브랜딩 / 아웃도어',
        category_en: 'Organic Food / Eco-friendly / Outdoor',
        description: '숲의 깊이와 햇살의 생기가 만나는 자리\n자연주의 속에서도 눈에 띄는 생동감을 만듭니다.',
        description_en: 'Where forest depth meets sunlight vitality\nCreates striking vividness within naturalism.',
        colors: [{ name: 'Wattle', hex: '#CCDA47' }, { name: 'Bottle Green', hex: '#0A3625' }],
    },
    {
        id: '06',
        name: 'Sand × Rust',
        category: '인테리어 / 홈리빙 / 빈티지 브랜딩',
        category_en: 'Interior / Home Living / Vintage Branding',
        description: '사막의 따뜻한 모래 위에 얹힌 녹슨 붉음\n오래된 것들이 가지는 고요한 아름다움.',
        description_en: 'Rusted red on top of warm desert sand\nThe quiet beauty of old things.',
        colors: [{ name: 'Sand', hex: '#E8D5B7' }, { name: 'Rust', hex: '#B7410E' }],
    },
    {
        id: '07',
        name: 'Ink × Gold',
        category: '출판 / 리테일 / 하이엔드 브랜딩',
        category_en: 'Publishing / Retail / High-end Branding',
        description: '깊은 먹빛 위에 빛나는 황금의 대비\n고전적이면서도 현대적인 품격을 담았습니다.',
        description_en: 'Brilliant gold contrast on deep ink\nEmbodies both classical and modern elegance.',
        colors: [{ name: 'Ink', hex: '#1A1A2E' }, { name: 'Gold', hex: '#D4AF37' }],
    },
    {
        id: '08',
        name: 'Blush × Slate',
        category: '패션 / 웨딩 / 라이프스타일 브랜딩',
        category_en: 'Fashion / Wedding / Lifestyle Branding',
        description: '부드러운 살구빛과 차가운 슬레이트의 균형\n감성적이면서도 트렌디한 인상을 전달합니다.',
        description_en: 'Balance of soft blush and cold slate\nConveys an emotional yet sophisticated impression.',
        colors: [{ name: 'Blush', hex: '#F4A7B9' }, { name: 'Slate', hex: '#475569' }],
    },
    {
        id: '09',
        name: 'Void × Neon',
        category: '게임 / 음악 / 스트릿웨어 브랜딩',
        category_en: 'Game / Music / Streetwear Branding',
        description: '완전한 어둠 속에서 터져 나오는 형광\n강렬하고 미래적인 에너지를 표현합니다.',
        description_en: 'Neon bursting out of complete darkness\nExpresses intense and futuristic energy.',
        colors: [{ name: 'Void', hex: '#0D0D0D' }, { name: 'Neon', hex: '#FF10F0' }],
    },
    {
        id: '10',
        name: 'Coral × Midnight',
        category: '엔터테인먼트 / K-POP / 영상 브랜딩',
        category_en: 'Entertainment / K-POP / Video Branding',
        description: '생동감 넘치는 코랄과 깊은 미드나잇의 대비\n힙하면서도 무게감 있는 브랜드를 만듭니다.',
        description_en: 'Vibrant coral contrast with deep midnight\nCreates a hip yet weighty brand identity.',
        colors: [{ name: 'Coral', hex: '#FF6B6B' }, { name: 'Midnight', hex: '#191970' }],
    },
    {
        id: '11',
        name: 'Cream × Forest',
        category: '유기농 브랜드 / 카페 / 농산물',
        category_en: 'Organic Brand / Cafe / Produce',
        description: '크리미한 배경과 숲의 깊이가 더해진 조화\n자연스럽고 건강한 이미지를 만듭니다.',
        description_en: 'Harmony of creamy background and forest depth\nCreates a natural and healthy image.',
        colors: [{ name: 'Cream', hex: '#FFF8DC' }, { name: 'Forest', hex: '#2D5A27' }],
    },
    {
        id: '12',
        name: 'Denim × Wheat',
        category: '캐주얼 패션 / 아웃도어 라이프',
        category_en: 'Casual Fashion / Outdoor Life',
        description: '워크웨어의 견고함과 밀밭의 따뜻함\n일상 속 진정성 있는 스타일을 표현합니다.',
        description_en: 'Ruggedness of workwear and warmth of wheat fields\nExpresses authentic everyday style.',
        colors: [{ name: 'Denim', hex: '#1560BD' }, { name: 'Wheat', hex: '#F5DEB3' }],
    },
    {
        id: '13',
        name: 'Samsung One UI Vivid',
        category: '모바일 인터페이스 / 역동적 사용자 경험',
        category_en: 'Mobile Interface / Dynamic UX',
        description: '삼성 One UI 특유의 생동감 넘치는 블루와 화이트\n깨끗하고 반응성 좋은 모바일 디자인을 완성합니다.',
        description_en: 'Samsung One UI\'s signature vivid blue and white. Completes a clean and responsive mobile design.',
        colors: [{ name: 'Samsung Blue', hex: '#034EA2' }, { name: 'One UI White', hex: '#FFFFFF' }],
    },
    {
        id: '14',
        name: 'Apple Glassmorphism',
        category: 'OS 인터페이스 / 미니멀 프리미엄',
        category_en: 'OS Interface / Minimal Premium',
        description: '애플의 투명한 유리 질감과 고대비 텍스트\n공간감이 느껴지는 세련된 UI를 제안합니다.',
        description_en: 'Apple\'s transparent glass texture and high-contrast text. Proposes a sophisticated UI with a sense of space.',
        colors: [{ name: 'Glass Frost', hex: '#F5F5F7' }, { name: 'Deep Space', hex: '#1D1D1F' }],
    },
];

const designGuides = [
    { 
        title: '60-30-10 법칙', 
        title_en: '60-30-10 Rule',
        desc: '주조색 60%, 보조색 30%, 포인트색 10%의 황금 비율로 균형 잡힌 디자인을 완성하세요.', 
        desc_en: 'Create a balanced design with the golden ratio: 60% primary, 30% secondary, and 10% accent color.',
        colors: ['#F5F5F7', '#D1D1D6', '#FF9500'] 
    },
    { 
        title: '보색 대비 활용', 
        title_en: 'Complementary Contrast',
        desc: '색상환에서 서로 마주 보는 두 색상을 조합하는 방식입니다. 강렬한 시각적 효과를 줍니다.', 
        desc_en: 'A method of combining two colors facing each other on the color wheel for a striking visual effect.',
        colors: ['#FF3B30', '#34C759'] 
    },
    { 
        title: '유사색 (Analogous)', 
        title_en: 'Analogous Colors',
        desc: '색상환에서 서로 인접한 3색을 사용합니다. 눈이 편안하고 조화로운 분위기를 연출합니다.', 
        desc_en: 'Uses three adjacent colors on the color wheel. Creates a comfortable and harmonious atmosphere.',
        colors: ['#007AFF', '#5856D6', '#AF52DE'] 
    },
    { 
        title: '톤온톤 (Tone-on-Tone)', 
        title_en: 'Tone-on-Tone',
        desc: '동일한 색상에서 채도와 명도만 다르게 조합합니다. 매우 안정적이고 깔끔한 이미지를 줍니다.', 
        desc_en: 'Combines the same hue with different saturation and brightness. Gives a stable and clean image.',
        colors: ['#0A84FF', '#64D2FF', '#B0E2FF'] 
    },
    { 
        title: '모노크롬 (Monochrome)', 
        title_en: 'Monochrome',
        desc: '하나의 색상을 베이스로 화이트, 블랙을 섞어 명도를 조절합니다. 극강의 심플함을 보여줍니다.', 
        desc_en: 'Uses a single base color and adjusts brightness with white and black. Shows extreme simplicity.',
        colors: ['#111111', '#888888', '#EEEEEE'] 
    },
    { 
        title: 'Apple: 글래스모피즘', 
        title_en: 'Apple: Glassmorphism',
        desc: '배경을 흐리게 처리(Blur)하고 반투명한 레이어를 쌓아 공간감을 만듭니다. 프리미엄한 느낌을 줍니다.', 
        desc_en: 'Creates a sense of space by blurring the background and stacking semi-transparent layers. Gives a premium feel.',
        colors: ['#FFFFFF', 'rgba(255,255,255,0.1)', '#000000'] 
    },
    { 
        title: 'Google: 머티리얼 쉐도우', 
        title_en: 'Google: Material Shadows',
        desc: '빛의 방향에 따른 그림자 깊이로 요소의 위계를 정합니다. 직관적인 클릭 범위를 알려줍니다.', 
        desc_en: 'Determines the hierarchy of elements through shadow depth according to the light direction. Indicates intuitive click areas.',
        colors: ['#4285F4', '#EA4335', '#FBBC05'] 
    }
];

const designFonts = [
    {
        id: 'f01',
        name: 'Inter',
        family: "'Inter', sans-serif",
        url: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap',
        category: 'Modern / UI',
        category_kr: '모던 / 인터페이스',
        pair: 'Roboto',
        note: '현대 웹 디자인의 표준과도 같은 폰트입니다. 압도적인 가독성을 자랑합니다.',
        note_en: 'The gold standard for modern web UI. Boasts incredible legibility.',
        sample: 'Design is not just what it looks like and feels like.'
    },
    {
        id: 'f02',
        name: 'Playfair Display',
        family: "'Playfair Display', serif",
        url: 'https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,700;0,900;1,700&display=swap',
        category: 'Luxury / Editorial',
        category_kr: '럭셔리 / 에디토리얼',
        pair: 'Montserrat',
        note: '고전적인 품격과 현대적인 세련미가 공존합니다. 제목용으로 탁월합니다.',
        note_en: 'Classical elegance meets modern sophistication. Perfect for headlines.',
        sample: 'The detail is not the detail. It is the design.'
    },
    {
        id: 'f03',
        name: 'Montserrat',
        family: "'Montserrat', sans-serif",
        url: 'https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;900&display=swap',
        category: 'Geometric / Tech',
        category_kr: '지오메트릭 / 테크',
        pair: 'Open Sans',
        note: '기하학적인 균형미가 돋보입니다. 브랜딩과 대담한 타이포그래피에 추천합니다.',
        note_en: 'Beautiful geometric balance. Recommended for branding and bold typography.',
        sample: 'Everything is designed. Few things are designed well.'
    },
    {
        id: 'f04',
        name: 'Lora',
        family: "'Lora', serif",
        url: 'https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,700;1,400&display=swap',
        category: 'Soft / Literary',
        category_kr: '감성 / 문학적',
        pair: 'Merriweather',
        note: '부드러운 곡선이 인상적인 세리프입니다. 장문의 본문이나 감성적인 글에 적합합니다.',
        note_en: 'A serif with soft curves. Ideal for long-form body text or emotional content.',
        sample: 'Good design is honest.'
    },
    {
        id: 'f05',
        name: 'Space Mono',
        family: "'Space Mono', monospace",
        url: 'https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&display=swap',
        category: 'Tech / Retro',
        category_kr: '테크 / 레트로',
        pair: 'Helvetica',
        note: '기하학적이고 그로테스크한 느낌의 모노스페이스입니다. 힙한 테크 디자인에 제격입니다.',
        note_en: 'A geometric, grotesque-style monospace. Perfect for hip tech designs.',
        sample: '0101 Code meets Art.'
    },
    {
        id: 'f06',
        name: 'Syne',
        family: "'Syne', sans-serif",
        url: 'https://fonts.googleapis.com/css2?family=Syne:wght@400;700;800&display=swap',
        category: 'Art / Avant-garde',
        category_kr: '예술 / 아방가르드',
        pair: 'Inter',
        note: '아방가르드하고 독창적인 형태를 가졌습니다. 예술적인 포스터나 강렬한 제목에 추천합니다.',
        note_en: 'Avant-garde and unique letterforms. Great for artistic posters or bold headlines.',
        sample: 'Typography is the voice of design.'
    },
    {
        id: 'f07',
        name: 'Nanum Myeongjo',
        family: "'Nanum Myeongjo', serif",
        url: 'https://fonts.googleapis.com/css2?family=Nanum+Myeongjo:wght@400;700;800&display=swap',
        category: 'Korean Classic',
        category_kr: '한국적 클래식',
        pair: 'Pretendard',
        note: '한국적인 정서와 정갈한 아름다움이 담긴 서체입니다. 신뢰감 있는 인상을 줍니다.',
        note_en: 'A typeface with Korean sentiment and clean beauty. Gives a trustworthy impression.',
        sample: '디자인은 보이지 않는 곳까지 완벽해야 합니다.'
    }
];

const uiTranslations = {
    kr: {
        nav_picker: '컬러 피커',
        nav_library: '라이브러리',
        nav_today: '오늘의 영감',
        nav_inspiration: '인스피레이션',
        nav_guide: '가이드',
        nav_my: '내 보관함',
        nav_fonts: '폰트 추천',
        font_playground_placeholder: '여기에 문구를 입력하여 폰트를 테스트해보세요...',
        font_designer_note: '디자이너의 노트',
        font_pairing: '추천 페어링',
        font_copy_stack: 'CSS 스택 복사',
        detail_mood: '색상 성격',
        detail_advice: '디자인 조언',
        detail_usage: '활용 분야',
        detail_similar: '유사한 색상 추천',
        detail_contrast: '텍스트 가독성 테스트',
        btn_copy_hex: 'HEX 복사',
        btn_copy_rgb: 'RGB 복사',
        btn_reset: '리셋',
        btn_save: '보관함에 저장',
        btn_share: '공유하기',
        btn_close: '닫기',
        search_placeholder: '색상 이름이나 태그 검색...',
        empty_fav: '보관함이 비어 있습니다.',
        select_family: '색 계열 선택',
        keyboard_guide_title: '조작 방법',
        keyboard_guide_1: 'R / G / B 클릭: 채널 선택',
        keyboard_guide_2: '← →: 선택 채널 미세 조정',
        keyboard_guide_3: '스페이스바: 룰렛 재시작',
        inspiration_subtitle: '멈추면 팔레트가 나타납니다 • 색을 클릭하면 Color Picker로 이동',
        guide_subtitle: '색을 다루는 기본적인 실용적인 지식들',
        library_subtitle: '용도별로 분류된 컬러 라이브러리',
        fonts_subtitle: '디자인의 완성도를 높여주는 마스터피스 폰트 추천',
        cat_all: '전체보기',
        cat_ui_web: 'UI/웹',
        cat_brand_global: '브랜딩',
        cat_nature: '자연/에코',
        cat_pastel: '감성/파스텔',
        cat_neon_modern: '네온/모던',
        cat_earth: '어스 톤',
        cat_monochrome: '모노크롬',
        btn_export_css: 'CSS / Tailwind 내보내기',
        my_palettes_title: '내 보관함',
        search_result_empty: '검색 결과가 없습니다.',
        footer_copy: '© 2024 RGBdom. 디자인을 위한 모든 색상.'
    },
    en: {
        nav_picker: 'Picker',
        nav_library: 'Library',
        nav_today: 'Inspo',
        nav_inspiration: 'Motion',
        nav_guide: 'Guide',
        nav_my: 'My Library',
        nav_fonts: 'Fonts',
        font_playground_placeholder: 'Type here to test fonts...',
        font_designer_note: "Designer's Note",
        font_pairing: 'Pairing',
        font_copy_stack: 'Copy CSS Stack',
        detail_mood: 'Mood',
        detail_advice: 'Design Advice',
        detail_usage: 'Usage',
        detail_similar: 'Similar Colors',
        detail_contrast: 'Contrast Test',
        btn_copy_hex: 'Copy HEX',
        btn_copy_rgb: 'Copy RGB',
        btn_reset: 'Reset',
        btn_save: 'Save to My',
        btn_share: 'Share Link',
        btn_close: 'Close',
        search_placeholder: 'Search names or tags...',
        empty_fav: 'Your library is empty.',
        select_family: 'Select Family',
        keyboard_guide_title: 'Controls',
        keyboard_guide_1: 'Click R/G/B: Select Channel',
        keyboard_guide_2: '← →: Fine Adjust Channel',
        keyboard_guide_3: 'Space: Restart Roulette',
        inspiration_subtitle: 'Stop to see palette • Click color to jump to Picker',
        guide_subtitle: 'Basic and practical knowledge of color',
        library_subtitle: 'Color library categorized by usage',
        fonts_subtitle: 'Masterpiece font recommendations to elevate your design',
        cat_all: 'All',
        cat_ui_web: 'UI/Web',
        cat_brand_global: 'Branding',
        cat_nature: 'Nature',
        cat_pastel: 'Pastel',
        cat_neon_modern: 'Neon/Modern',
        cat_earth: 'Earth Tone',
        cat_monochrome: 'Monochrome',
        btn_export_css: 'Export CSS / Tailwind',
        my_palettes_title: 'My Palettes',
        search_result_empty: 'No results found.',
        footer_copy: '© 2024 RGBdom. All colors for design.'
    }
};
